audit_header: false
title: Real Estate Video Blog with Scott Hoffman
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title: 
    url: 
show_custom_links_new_tab: false
custom_links_new_tab:
  - title: 
    url: 

client:
  name: Scott Hoffman
  title:
  license_number:
  about_markdown: |
    Through his highly professional, informed and diligent approach, Scott Hoffman provides outstanding expertise and professional representation to his valued clients. As a client looking to purchase and/or, you may rely on Scott to always skillfully apply himself in order to accomplish and make your real estate dreams come true. His honest, accurate and forthright guidance lies at the heart of Scott’s personal service to his clients. When working with Scott, his clients always receive real estate advice based on careful analysis of the market and a deliberately mindful and cautious approach on their behalf. His wealth of real estate experience clearly allows him to skillfully advise his clients in making balanced decisions about their real estate investment. Scott is extremely attentive and responsive to each client's specific requirements and is very thorough in providing constant attention and communication regarding the important details of the transaction.
  brand: Hoffman Realty Group
  brokerage: Keller Williams Preferred Realty
  market: Raleigh
  address: 7751 Brier Creek Parkway, Ste. 100 Raleigh, NC 27617<br>Keller Williams Outer Banks Realty<br>5595 N Croatan Hwy<br>Southern Shores, NC 27949
  phone: 919-281-3250
  phone_type:
  phone2: 
  phone2_type:
  email: scott@thehoffmanrealtygroup.com
  url: https://RaleighRealEstateSearch.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.raleighrealestatesearch.com/cma/property-valuation/
  second_CTA_text: Triangle Area Home Search
  second_CTA_URL: https://www.raleighrealestatesearch.com/search/advanced_search/
  third_CTA_text: Outer Banks Home Search
  third_CTA_URL: https://www.searchobxhomes.com/search/advanced_search/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.raleighrealestatesearch.com/cma/property-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.raleighrealestatesearch.com/search/advanced_search/

third_sidebar_CTA:
  - CTA_image_path3: /img/cta-images/003.jpg
    CTA_title3: "Looking for an Outer Banks home?"
    CTA_text3: "Search the entire MLS for your Outer Banks Home."
    CTA_link_text3: "Outer Banks Home Search"
    CTA_url3: https://www.searchobxhomes.com/search/advanced_search/  

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/thehoffmanrealtygroup?fref=ts
  linkedin_url: https://www.linkedin.com/in/thescotthoffmanteam/
  youtube_url: https://www.youtube.com/user/thescotthoffmanteam
  twitter_url: https://twitter.com/scotthoffman
  instagram_url: https://www.instagram.com/thehoffmanrealtygroup/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://podcasts.apple.com/us/podcast/raleigh-real-estate-podcast-with-scott-hoffman/id1481265584

podcast:
  title: '-- MARKET -- Real Estate Podcast with Scott Hoffman'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Scott Hoffman'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: North Carolina Real Estate Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#C42134'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 2px
  w_shadow: 2px
  shadow_spread: 9px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
